config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :courses

  root 'page#default'
  get "/about" => "page#about"

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  has_many :resources
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :course
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def is_owned_by(user)
    return false if !user
    user.id == uploaded_by_user_id
  end

end

app/models/user.rb
class UserValidator < ActiveModel::Validator
  def validate(record)
    unless record.email.end_with? "@education.nsw.gov.au"
      record.errors[:base] << "Only school email accounts may be used"
    end
  end
end
 
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates_with UserValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:subject, :coordinator, :description, :image)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
    def default
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
    @resource.course_id = params[:course] || nil
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:course_id, :lesson_date, :url, :image, :uploaded_by_user_id, :description)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :email, :password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :coordinator %><br>
    <%= f.text_field :coordinator %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @course %> |
<%= link_to 'Back to courses', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<div style="float: right" class="btn btn-medium btn-round">
  <%= link_to 'New Course', new_course_path if current_user && current_user.is_sysadmin %>
</div>

<h1>Courses</h1>

<div class="course-index-items">
  <% @courses.each do |course| %>
    <%= link_to course, class: "course-index-item" do %>
      <div class="image"><%= image_tag course.image.url(:thumb) %></div>
      <div class="text">
        <div><%= course.subject %></div>
        <div><%= course.coordinator %></div>
        <div><%= course.description %></div>
        <div><%= "#{pluralize(course.resources.size, 'resource')}" %></div>
      </div>
    <% end %>
  <% end %>
</div>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Cancel', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div style="float: right" class="btn btn-medium btn-round">
  <%= link_to 'New Resource', new_resource_path(course: @course) if current_user %>
</div>

<table>
  <tr>
    <td>
      <p>
        <%= image_tag @course.image.url(:thumb), class: :'course-image thumb' %>
      </p>
    </td>
    <td>
      <h2><%= @course.subject %></h2>
      <h3><%= @course.coordinator %></h3>
      <h4><%= @course.description %></h4>
    </td>
  </tr>
</table>

<% if @course.resources.empty? %>
  <p>
    <strong>No resources yet!</strong>
  </p>
<% else %>
  <strong>Resources:</strong>
  <p>
    <% @course.resources.order(updated_at: :desc).each do |r| %>
      <%= render partial: 'resources/resource', locals: {resource: r, hide_course_name: true} %>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit |', edit_course_path(@course) if current_user && current_user.is_sysadmin %>
<%= link_to 'Delete this course |', @course, method: :delete, data: { confirm: 'Are you sure?' } if current_user && current_user.is_sysadmin %>
<%= link_to 'Back', courses_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="navbar-toggleable-xs" id="exCollapsingNavbar2">

      <a class="nav-item navbar-brand logo"></a>

      <%= link_to "home", root_path, class: 'navbar-brand' %>
      <%= link_to "about", about_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
        <%= link_to "courses", courses_path, class: 'navbar-brand' %>
        <%= link_to "profile", edit_user_registration_path, class: 'navbar-brand' %>
        <%= link_to "log out", destroy_user_session_path, method: 'delete', class: 'navbar-brand' if user_signed_in? %>
      <% else %>
        <%= link_to "sign up", new_user_registration_path, class: 'navbar-brand' unless user_signed_in? %>
        <%= link_to "log in", new_user_session_path, class: 'navbar-brand' unless user_signed_in? %>
      <% end %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Northlakes class catchup" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Workspace" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/page/about.html.erb
<h1>About Northlakes Coder Girls</h1>
<p>About us!</p>

app/views/page/default.html.erb
<div class="jumbotron">
  <h2>Northlakes Class Catchup</h2>
  <h5>Helping students catch up on missed classwork.</h5>
  <h6>Students can register, join other students in their course and then upload coursework images, notes or links for other students to use.</h6>
  <p>Need to know what you missed?  Find out here!</p>
  <% unless user_signed_in? %>
    <p>
      <%= link_to "Sign up", new_user_registration_path %>
      or
      <%= link_to "Log In", new_user_session_path %>
    </p>
  <% end %>
</div>
<div class="footer">
  <h6>Made with &lt;3 by <a href="/about">Northlakes Coder Girls</a></h6>
</div>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= collection_select(:resource, :course_id, Course.all, :id, :subject, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :lesson_date %><br>
    <%= f.date_select :lesson_date %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>

  <div>Uploaded by: <%= User.find(@resource.uploaded_by_user_id).email if User.exists?(@resource.uploaded_by_user_id) %></div>
  <%= f.hidden_field :uploaded_by_user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div style="display:inline">
    <%= link_to resource, class: 'resource-index-item' do %>
      <div class="image"><%= image_tag resource.image.url(:thumb) %></div>
      <div class="text">
        <% unless hide_course_name %>
            <div><%= resource.course ? resource.course.subject : "" %></div>
        <% end %>
        <div><%= resource.description %></div>
        <div><%= resource.lesson_date %></div>
        <div class="resource-link"><%= resource.url %></div>
      </div>
    <% end %>
</div>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<div style="float: right" class="btn btn-medium btn-round">
  <%= link_to 'New Resource', new_resource_path if current_user %>
</div>
<h1>Resources</h1>

<div>
  <% @resources.each do |resource| %>
    <%= render partial: 'resources/resource', locals: {resource: resource, hide_course_name: false} %>
  <% end %>
</div>

<br>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Cancel', resources_path %>

app/views/resources/show.html.erb
<div style="margin: 2em">
  <p id="notice"><%= notice %></p>
  
  <p style="display:inline-block;margin-right:2em">
    <%= link_to @resource.image.url, target: :_blank do %>
      <%= image_tag @resource.image.url(:medium), class: :'reource-image medium' %>
    <% end %>
  </p>
  <div style="display:inline-block">
    <p>
      <strong>Course:</strong>
      <%= @resource.course ? @resource.course.subject : "" %>
    </p>
    
    <p>
      <strong>Description:</strong>
      <% if @resource.description.blank? %>
        -
      <% else %>
        <%= @resource.description %>
      <% end %>
    </p>
    
    <p>
      <strong>Lesson date:</strong>
      <%= @resource.lesson_date %>
    </p>
    
    <p>
      <strong>URL:</strong>
      <% if @resource.url.blank? %>
        -
      <% else %>
        <%= link_to @resource.url %>
      <% end %>
    </p>
    
    <p>
      <strong>Uploaded by:</strong>
      <%= User.find(@resource.uploaded_by_user_id).email if User.exists?(@resource.uploaded_by_user_id) %>
    </p>
    <%= link_to 'Edit |', edit_resource_path(@resource) if @resource.is_owned_by(current_user) or (current_user and current_user.is_sysadmin) %>
    <%= link_to 'Delete this resource |', @resource, method: :delete, data: { confirm: 'Are you sure?' } if @resource.is_owned_by(current_user) or current_user and current_user.is_sysadmin %>
    <%= link_to 'Go to course', @resource.course ? course_path(@resource.course) : resources_path %>
  </div>
</div>